apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapi-solution-api
  namespace: prod
  labels:
    app: swapi-solution-api
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swapi-solution-api
  template:
    metadata:
      labels:
        app: swapi-solution-api
        env: prod
    spec:
      containers:
      - name: swapi-solution-api
        image: olagunju/swapi-solution-api:prod-latest
        volumeMounts:
        - name: config
          mountPath: /app/.env
          subPath: .env
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        secret:
          secretName: swapi-solution-api-prod-config
          items:
          - key: .env
            path: .env