apiVersion: v1
kind: Service
metadata:
  name: swapi-solution-api-service
  namespace: prod
  labels:
    app: swapi-solution-api
    env: prod
spec:
  selector:
    app: swapi-solution-api
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
  type: LoadBalancer