apiVersion: v1
kind: Service
metadata:
  name: swapi-solution-api-service
  namespace: stage
  labels:
    app: swapi-solution-api
    env: stage
spec:
  selector:
    app: swapi-solution-api
    env: stage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
  type: LoadBalancer