name: Stage Build and Deploy

on:
  push:
    branches:
      - stage

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  AWS_REGION: us-west-2
  IMAGE_REPO: olagunju/swapi-solution-api
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        id: tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials for EKS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: List EKS clusters
        run: aws eks list-clusters --region ${{ env.AWS_REGION }}
      - name: Setup Kubectl and Update kubeconfig
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name busha-cluster
      - name: Update deployment file
        run: |
          sed -i 's|image: .*|image: ${{ env.IMAGE_REPO }}:${{ github.sha }}|' ./k8s/stage/deployment.yml
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s/stage/deployment.yml
          kubectl rollout status deployment/swapi-solution-api -n stage